# digest for alpine:3.10.2
FROM alpine@sha256:72c42ed48c3a2db31b7dafe17d275b634664a708d901ec9fd57b1529280f01fb

# Max user
RUN addgroup -g 255999 -S app && \
    adduser -u 255999 -S app -G app

COPY /aws-service-quotas-exporter /home/app/aws-service-quotas-exporter

RUN chmod +x /home/app/aws-service-quotas-exporter

USER app

EXPOSE 9090

ENTRYPOINT ["/home/app/aws-service-quotas-exporter"]
