go_library(
    name = "service_quotas",
    srcs = [
        "service_quotas.go",
        "vpc_limits.go",
    ],
    visibility = ["//..."],
    deps = [
        "//third_party/go:aws-sdk-go",
        "//third_party/go:errors",
    ],
)
